
CREATE DATABASE Semantix;

CREATE TABLE Clientes (
	Id int IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	RG VARCHAR(9) NOT NULL,
	CPF VARCHAR(11) NOT NULL
);

CREATE TABLE Telefones (
	Id int IDENTITY(1,1) PRIMARY KEY,
	Numero VARCHAR(100) NOT NULL,
	ClienteId INT NOT NULL
);

CREATE TABLE Enderecos (
	Id int IDENTITY(1,1) PRIMARY KEY,
	Rua VARCHAR(255) NOT NULL,
	Bairro VARCHAR(255) NOT NULL,
	Numero VARCHAR(255) NOT NULL,
	Cidade VARCHAR(255) NOT NULL,
	Estado VARCHAR(255) NOT NULL,
	CEP VARCHAR(8),
	Complemento VARCHAR(500),
	ClienteId INT NOT NULL
);

ALTER TABLE Telefones ADD CONSTRAINT FK_TELEFONE_CLIENTE FOREIGN KEY(ClienteId) REFERENCES Clientes(Id);
ALTER TABLE Enderecos ADD CONSTRAINT FK_ENDERECOS_CLIENTE FOREIGN KEY(ClienteId) REFERENCES Clientes(Id);
